export const COLORS = {
	neutral: [
		"bg-neutral-900",
		"dark:bg-white",
		"dark:text-neutral-900",
		"text-neutral-100",
		"hover:border-neutral-700",
		"border-neutral-900",
		"dark:hover:border-neutral-300",
		"hover:bg-white",
		"dark:hover:bg-black",
		"dark:hover:text-white",
		"hover:text-neutral-900",
	],
	blue: [
		"bg-blue-600",
		"text-white",
		"border-blue-600",
		"hover:bg-white",
		"hover:text-blue-600",
		"dark:hover:bg-black",
	],
	red: [
		"bg-red-500",
		"text-white",
		"border-red-500",
		"hover:bg-white",
		"hover:text-red-500",
		"dark:hover:bg-black",
		"dark:bg-red-800",
		"dark:border-red-800",
		"dark:hover:border-red-500",
	],
	yellow: [
		"bg-yellow-600",
		"text-white",
		"border-yellow-600",
		"hover:bg-white",
		"hover:text-yellow-600",
		"dark:hover:bg-black",
		"dark:bg-yellow-700",
		"dark:border-yellow-700",
	],
	green: [
		"bg-green-600",
		"text-white",
		"border-green-600",
		"hover:bg-white",
		"hover:text-green-600",
		"dark:hover:bg-black",
		"dark:bg-green-800",
		"dark:border-green-800",
		"dark:hover:text-green-800",
	],
};
